- name: Create mongo container
  community.docker.docker_container:
    name: mongo
    image: mongo:8.0
    state: started
    restart: true
    restart_policy: unless-stopped
    ports:
      - "27017:27017"
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ mongo_user }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_password }}"
